_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.2
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.2
            "13": darwin-arm64
